import { chromium } from 'playwright';
const url = process.argv[2];
const b = await chromium.launch({ headless:true });
const p = await b.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto(url,{waitUntil:'networkidle',timeout:45000});
await p.waitForTimeout(1500);
const r = await p.evaluate(()=>{
  const sections=document.querySelectorAll('main .section').length;
  const blocks=[...document.querySelectorAll('[data-block-name]')].map(b=>b.dataset.blockName);
  const decorated=[...document.querySelectorAll('.block[data-block-status="loaded"]')].length;
  const h1=document.querySelectorAll('h1').length;
  const navLinks=document.querySelectorAll('header nav a').length;
  const footLinks=document.querySelectorAll('footer a').length;
  const imgs=[...document.querySelectorAll('img')];
  const broken=imgs.filter(i=>i.complete && i.naturalWidth===0).length;
  const appear=document.body.classList.contains('appear');
  const pillarGrid=document.querySelector('.cards.pillars ul');
  const pillarDisplay=pillarGrid?getComputedStyle(pillarGrid).display:'none';
  return {sections,blocks,decorated,h1,navLinks,footLinks,imgCount:imgs.length,broken,appear,pillarDisplay};
});
console.log('pageerrors:',errs.length?errs:'none');
console.log(JSON.stringify(r,null,1));
await b.close();
