import { chromium } from 'playwright';
const file = process.argv[2];
const b = await chromium.launch({ headless:true });
const p = await b.newPage();
await p.setViewportSize({width:1280,height:900});
const errors=[];
p.on('pageerror',e=>errors.push(e.message));
await p.goto('file://'+file,{waitUntil:'networkidle',timeout:30000});
await p.waitForTimeout(800);
const r = await p.evaluate(()=>{
  const sections=document.querySelectorAll('main section, [data-block]').length;
  const pillars=document.querySelector('.pillars-grid');
  const deals=document.querySelector('.deals-grid');
  const gd=pillars?getComputedStyle(pillars).display:'none';
  const gd2=deals?getComputedStyle(deals).display:'none';
  const h1=document.querySelectorAll('h1').length;
  const bodyText=document.body.innerText.length;
  return {sections,pillarsDisplay:gd,dealsDisplay:gd2,h1count:h1,bodyText};
});
console.log('errors:',errors.length?errors:'none');
console.log(JSON.stringify(r));
await b.close();
